import SwiftUI

/// Sheet for regenerating an episode's transcript with a chosen engine + language.
struct TranscriptRegenerateSheet: View {
    @Environment(\.dismiss) private var dismiss
    @Bindable var viewModel: EpisodeDetailViewModel

    private var effectiveEngine: TranscriptEngine {
        viewModel.transcript.selectedTranscriptEngine ?? TranscriptEngine(
            rawValue: UserDefaults.standard.string(forKey: "transcriptEngine") ?? ""
        ) ?? .appleSpeech
    }

    private var canRegenerate: Bool {
        if effectiveEngine == .yapServer {
            return viewModel.hasLocalAudio || !(viewModel.audioURL ?? "").isEmpty
        }
        return viewModel.hasLocalAudio
    }

    private var regenerateDescription: String {
        if effectiveEngine == .yapServer && !viewModel.hasLocalAudio {
            return "This replaces the current transcript with one generated by your Yap server from the episode's remote audio."
        }
        return "This replaces the current transcript with one generated from the downloaded audio and preserves accurate timestamps."
    }

    private func resolvedLanguage(_ code: String, for engine: TranscriptEngine) -> String {
        guard !code.isEmpty else { return code }
        let locales = SettingsViewModel.locales(for: engine)
        let lower = code.lowercased()

        if locales.contains(where: { $0.id == lower }) { return lower }
        if let match = locales.first(where: { $0.id.hasPrefix(lower + "-") }) {
            return match.id
        }

        let base = lower.split(separator: "-").first.map(String.init) ?? lower
        if let match = locales.first(where: { $0.id == base || $0.id.hasPrefix(base + "-") }) {
            return match.id
        }

        return lower
    }

    private var pickerLocales: [SettingsViewModel.TranscriptLocaleOption] {
        let standard = SettingsViewModel.locales(for: effectiveEngine)
        let podcastLang = viewModel.podcastLanguage.lowercased()
        let resolved = resolvedLanguage(podcastLang, for: effectiveEngine)

        if standard.contains(where: { $0.id == resolved }) {
            return standard
        }

        let displayName = Locale.current.localizedString(forLanguageCode: podcastLang) ?? podcastLang
        let dynamic = SettingsViewModel.TranscriptLocaleOption(
            id: podcastLang,
            name: "\(displayName) (podcast)"
        )
        return [dynamic] + standard
    }

    private var selectedLanguageBinding: Binding<String> {
        Binding(
            get: {
                if effectiveEngine == .whisper {
                    return viewModel.transcript.selectedTranscriptLanguage ?? "auto"
                }
                return resolvedLanguage(
                    viewModel.transcript.selectedTranscriptLanguage ?? viewModel.podcastLanguage,
                    for: effectiveEngine
                )
            },
            set: { newValue in
                if effectiveEngine == .whisper {
                    viewModel.transcript.selectedTranscriptLanguage = (newValue == "auto") ? nil : newValue
                } else {
                    viewModel.transcript.selectedTranscriptLanguage = newValue
                }
            }
        )
    }

    var body: some View {
        NavigationStack {
            Form {
                Section {
                    Text(regenerateDescription)
                }

                Section {
                    Picker("Engine", selection: Binding(
                        get: { effectiveEngine },
                        set: { newEngine in
                            viewModel.transcript.selectedTranscriptEngine = newEngine
                            if newEngine == .whisper {
                                return
                            }

                            if let selected = viewModel.transcript.selectedTranscriptLanguage {
                                let resolved = resolvedLanguage(selected, for: newEngine)
                                let isSupported = SettingsViewModel.locales(for: newEngine).contains {
                                    $0.id == resolved
                                }
                                if !isSupported {
                                    viewModel.transcript.selectedTranscriptLanguage = nil
                                }
                            }
                        }
                    )) {
                        ForEach(TranscriptEngine.allCases) { engine in
                            Label(engine.displayName, systemImage: engine.systemImage)
                                .tag(engine)
                        }
                    }

                    Picker("Language", selection: selectedLanguageBinding) {
                        // `selectedLanguageBinding` reports "auto" whenever
                        // Whisper is selected with no explicit language, so the
                        // tag has to exist or the selection matches nothing and
                        // SwiftUI warns about undefined results.
                        if effectiveEngine == .whisper {
                            Text("Auto-detect").tag("auto")
                        }
                        ForEach(pickerLocales) { locale in
                            Text(locale.name).tag(locale.id)
                        }
                    }
                } header: {
                    Text("Generation Settings")
                } footer: {
                    if effectiveEngine == .whisper {
                        Text("Auto-detect identifies the language automatically.")
                    } else if effectiveEngine == .yapServer {
                        Text("Yap Server transcribes using the podcast language by default.")
                    } else {
                        Text("Apple Speech uses the podcast language by default and requires a model download per language.")
                    }
                }

                Section {
                    Button("Regenerate from Audio") {
                        dismiss()
                        viewModel.transcript.regenerateTranscript()
                    }
                    .disabled(!canRegenerate)
                }

                if !canRegenerate {
                    Section {
                        Text("Download the episode audio before regenerating the transcript.")
                    }
                }
            }
            .navigationTitle("Regenerate Transcript")
            #if os(iOS)
            .navigationBarTitleDisplayMode(.inline)
            #endif
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") {
                        dismiss()
                    }
                }
            }
        }
        .presentationDetents([.medium, .large])
        .presentationDragIndicator(.visible)
    }
}
